name:                protocol
version:             0.0.0.0
github:              "Nickske666/protocol"
license:             BSD3
author:              "Nick Van den Broeck"
maintainer:          "nick.van.den.broeck666@gmail.com"
copyright:           "2018 Nick Van den Broeck"

description:         Nowhere yet

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10 && < 1.0
- validity >= 0.4.0 && < 0.5.0
- text >= 1.2 && < 2.0
- network >= 2.6 && < 3.0
- optparse-applicative >= 0.14 && < 0.15
- array >= 0.5 && < 0.6
- attoparsec >= 0.13 && < 0.14

library:
  source-dirs: src
  exposed-modules:
  - Protocol
  - Protocol.Connection
  - Protocol.Process
  - Protocol.Reply
  - Protocol.Request
  - Protocol.ServerLocation
  - Protocol.Socket
  - Protocol.StartClient

executables:
  protocol:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - protocol

tests:
  protocol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - protocol
